location_provider: manual # or automatic. Uses longitude and latitude if manual
longitude: 4.9558081
latitude: 52.3545352
ping_address: 145.109.6.27
modules_directory: ./modules
temperature_measurement_location: Schiphol
temperature_threshold: 10
run_name: light_on
start_name: start
stop_name: stop
modules:
  - modules.aex_is_up
  - modules.always_on
  # - modules.gesture_recognizer
  - modules.kan_ik_een_korte_broek_aan
  - modules.ping_martin
  - modules.schiphol_temperature
  - modules.time_getter
  # - modules.trump_tweet
