server_ip: 146.50.60.16
server_port: 50007
location_provider: manual # or automatic. Uses longitude and latitude if manual
longitude: 4.9558081
latitude: 52.3545352
ping_address: localhost
modules_directory: ./modules
temperature_measurement_location: Schiphol
temperature_threshold: 10
run_name: light_on
start_name: start
stop_name: stop
sleep_seconds: 1
testing: False
modules:
  modules.aex_is_up:
    pos:
      - 0 # x-position, left is 0, positive is to the right
      - 0 # y-position, top is 0, positive is down
    size:
      - 2 # x-size / width
      - 2 # y-size / height
  modules.always_on:
    pos:
      - 3
      - 0
    size:
      - 2
      - 2
  # modules.gesture_recognizer:
  #  pos:
  #    - 30
  #    - 14
  #  size:
  #    - 2
  #    - 2
  modules.kan_ik_een_korte_broek_aan:
    pos:
      - 6
      - 0
    size:
      - 2
      - 2
  modules.ping_martin:
    pos:
      - 0
      - 3
    size:
      - 2
      - 2
  modules.schiphol_temperature:
    pos:
      - 3
      - 3
    size:
      - 2
      - 2
  modules.time_getter:
    pos:
      - 6
      - 3
    size:
      - 2
      - 2
  # modules.trump_tweet:
  #  pos:
  #    - 25
  #    - 8
  #  size:
  #    - 1
  #    - 7
